name: Test
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        entry:
          - { ruby: '2.6', allowed-failure: false }
          - { ruby: '2.7', allowed-failure: false }
          - { ruby: '3.0', allowed-failure: false }
          - { ruby: ruby-head, allowed-failure: false }
    name: test (${{ matrix.entry.ruby }})
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.entry.ruby }}
      - run: sudo apt-get install -y valgrind
      - uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('Gemfile') }}
          restore-keys: ${{ runner.os }}-gems-
      - run: bundle install --jobs=3 --retry=3 --path=vendor/bundle
      - run: bundle exec rake
        continue-on-error: ${{ matrix.entry.allowed-failure }}
